### PR TITLE
Create Cli_pt_BR.properties

### PR DESCRIPTION
**Pull request by arthurbarret0**
CLI translation into Brazilian Portuguese

### CODE REVIEW

**Comment by MoonstruckDev** [comment]
Let me know if you want them since I can offer the French translation

 (i'm even in bisect server if you want to ping)

**Comment by Griefed** [comment]
> Let me know if you want them since I can offer the French translation
> 
> (i'm even in bisect server if you want to ping)

That would be fantastic. I'll probably restructure the translations to make it easier for people to add theirs. Afterwards, I'll get back to you. Thank you for the offer! 😊

**Comment by Griefed** [comment]
> Let me know if you want them since I can offer the French translation
> 
> (i'm even in bisect server if you want to ping)

Restructuring done! :) If you're still interested in adding french translations, please check out the `develop`-branch: https://github.com/Griefed/ServerPackCreator/tree/develop/serverpackcreator-api/src/commonMain/i18n

**Comment by MoonstruckDev** [comment]
Will do! just need to find the time!

**Pull request merged**
