### PR TITLE
feat: Making the default config file empty, writing checks of its values

### PR DESCRIPTION
**Pull request by whitebear60**
- [x] Make the default config file empty
- [x] Write checks of the String config values
- [x] Write checks of the List config values
- [x] Check that the mod pack directory exists before creating a server pack; throw an exception if it doesn't exist.
- [ ] Write checks of the Boolean config values
- [x] Write checks for Minecraft and mod loader versions

Implementing the feature described in #13

### CODE REVIEW

**Comment by Griefed** [comment]
Going to review these changes on saturday. Thanks!

**Comment by Griefed** [comment]
Ah okay, then I'll just take a peek on saturday. Curious as to what you've come up with. Thanks for your hard work. :)

**Comment by Griefed** [comment]
Heya @whitebear60, I've noticed you've added a config variable to the config file relating to client mods. May I ask that you remove said variable and leave the config file unchanged?
The reason behind this is that I want users to be able to update to newer versions of SPC without having to manually migrate their config file.
Also, it is safe to assume that a given modpack has client mods in it. If it doesn't, then SPC will simply not delete any files, therefore rendering the `clientModsExist` obsolete. 

Completely my fault, as it didn't occur to me to include it in Contributing.md. I've added that a couple of minutes ago. There's no way you could've known that I want users to be able to update their SPC version without touching their config file.

Cheers,
Griefed

**Comment by whitebear60** [comment]
Understood.

**Comment by whitebear60** [comment]
Wrote Minecraft version checks, if I will have time next week, I will try to write Fabric and Forge version checks.

**Comment by whitebear60** [comment]
Don't understand why Github marks my files as ones that have conflicts, please help me to decide what to do with that.

**Comment by whitebear60** [comment]
Also removed my version of Java path check as it is already implemented in 0437577

**Comment by Griefed** [comment]
> Don't understand why Github marks my files as ones that have conflicts, please help me to decide what to do with that.

Started checking the files. GitHub errors probably due to both of us working on the same files and our changes clashing, so git doesn't know what to do.

**Comment by Griefed** [comment]
Resolved conflicts.
Re-organized a couple of checks in Main.
Used the opportunity to fix smaller erros in ServerSetup
Added documentation for your new `isMinecraftVersionCorrect`

**Comment by whitebear60** [comment]
Thanks. I haven't written checks for empty Boolean values, as if they will be empty, config parse exception will be thrown by config library.

**Comment by Griefed** [comment]
Yup, I've taken a look at this myself just now. It's good that the application exits if the boolean is set incorrectly, but it would be nice if we could swap that with a more nicer looking error message. 
Gotta say, your changes are great. I had great fun going through them and they gave me a couple of ideas. Thank you very much for your contributions! 🤘

**Comment by whitebear60** [comment]
> Yup, I've taken a look at this myself just now. It's good that the application exits if the boolean is set incorrectly, but it would be nice if we could swap that with a more nicer looking error message.
> Gotta say, your changes are great. I had great fun going through them and they gave me a couple of ideas. Thank you very much for your contributions! 🤘

Just surround config parsing instructions with try/catch and write in catch block a message and then sys.exit(1).

**Comment by Griefed** [comment]
*headdesk* Of course, why didn't I think of that. 😂 Thanks man!

**Comment by whitebear60** [comment]
Now will be trying to implement #8 , but I haven't worked with Java arguments before, so it could waste too many time. Now you can close #13 and assign me to #8.

**Comment by whitebear60** [comment]
I have started programming in Java just recently too :)

**Pull request merged**
